### ISSUE TITLE
Agregar confirmación antes de efectivizar el kill-9

### ISSUE THREAD

**Issue by emilioplatzer** [codenautas/kill-9#2]
Actualmente al hacer kill-9 el módulo verifica que coincida el parametro pid (pasado en el GET) con el que está en la configuración del módulo. Si coinciden mata el proceso. 

Hay que agregar un paso intermedio, lo que tiene que pasar es:
1. Luego de verificar que coincida el PID debe enviar un html con un form muy simple que contenga un botón que haga submit (ese formulario debe contener unos parámetros aleatorios que venzan rápido), el método debe ser POST
2. Al recibir el POST si los parámetros son correctos y no vencieron debe proceder a hacer el kill y a dar el feedback correspondiente, si no coinciden debe indicar que los parámetros están vencidos.

Los parámetros deben ser dos `{random: Math.random(), hash:crypto.md5(new Date().getTime() + process.pid)}` 

El HTML debe ser algo parecido a:

``` html
<form method=POST action="{{locationPost}}">
{{messageConfirm}}
<input name=masterpass type="password">
<input name=submit type="submit" value="{{messageSubmit}}"> 
<input name=params type="hidden" value="{{params}}">
</form>
```

Agregar los siguientes parámetros: 
- locationPost: a dónde colgar el POST (default: mismo url especificado en location)
- messageConfirm: mensaje de confirmación (default: "confirm kill-9")
- messageSubmit: mensaje para el botón de confirmación (default: "Ok")
- confirmTimeout: milisegundos de vigencia de los parámetros de confirmación (default: 1 minuto)
- masterPass: obligatorio (si no aborta el servidor) la clave que debe introducirse

Corregir los tests (ya no habrá muerte directa sin confirmación). El parámetro `confirmTimeout` está especialmente puesto para que el test no sea tan plomo. 

Subirlo a la versión 0.4.0 (breaking change)

**Comment by diegoefe** [comment]
Dudas acerca de "params":
1. "random" y "hash" los querés en la misma variable? Para qué? Los concateno con un separador?
2. Para qué sirve "random"? (si es para evitar el caché, se pueden usar los headers)
3. Cómo calculo "hash" para validarlo? (si ese es el propósito). Su existencia parecería superponerse con el de confirmTimeout. En cualquiera de los casos cambia con cada refresh.

**Comment by emilioplatzer** [comment]
1. JSON del objeto que contiene a ambos
2. Para que si coinciden la fecha y el PID haya algo que seguro es distinto
3. con el GET que manda el formulario calculás el random y hash lo enviás y te lo guardás, además registrás el timestart y te lo guardás. Al recibir el POST controlás que random y hash sean los enviados y que el tiempo no se haya pasado.
