### ISSUE TITLE
Hashear masterPass en el cliente, postear y comparar en el server

### ISSUE THREAD

**Issue by diegoefe** [codenautas/kill-9#3]
Mejora la seguridad

**Comment by emilioplatzer** [comment]
Excelente idea.

**Comment by diegoefe** [comment]
Ya está pero no pude probarlo en Linux. Por tanto no voy a publicarlo. Fijate si podés probarlo vos.

**Comment by emilioplatzer** [comment]
Me fijo

**Comment by emilioplatzer** [comment]
1) ¿Por qué se necesitan dos versiones del middleware de body parser?

``` js
    killer.use(bodyParser.json());
    killer.use(bodyParser.urlencoded({extended:true}));
```

2) Dudo en poner killer.use del middleware correspondiente acá. Me pregunto si no habría que verificar antes si no está o darlo por supuesto o si es inocuo que esté varias veces incluido.

**Comment by diegoefe** [comment]
1) Mi error. Por no leer la documentación bien creí que tenía que agregar los dos.
2) Yo lo agregué ahí porque entendí que era el lugar más acotado. No me parece buena solución usar get si req.body no está definido, porque , por ejemplo, el query string queda registrado en todos los cachés.

**Comment by emilioplatzer** [comment]
2) estoy de acuerdo. Es solo si es la última opción. De todos modos en un servidor en serio esto tiene que hacerse con https
